apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-counter
spec:
  ingressClassName: nginx
  rules:
    - host: {{ if .Values.backendHost}}{{ .Values.backendHost }}{{ else }}counter-backend-{{.Release.Namespace}}-{{.Release.Name}}.k8sdb.cpas.cz{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}-counter
                port:
                  number: 80
