apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-counter
data:
  EXTRA_TEXT: {{ .Values.EXTRA_TEXT_HELLO }} {{ .Values.EXTRA_TEXT_VERSION }}
  SLOW_START: {{ .Values.SLOW_START | quote }}
