apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: {{ if .Values.frontendHost}}{{ .Values.frontendHost }}{{ else }}counter-frontend-{{.Release.Namespace}}-{{.Release.Name}}.k8sdb.cpas.cz{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}-frontend
                port:
                  number: 80
